### ISSUE TITLE
src.RecvMsg(f) that in handler.forwardClientToServer product rpc error: code = Internal desc = grpc: failed to unmarshal the received message string field contains invalid UTF-8

### ISSUE THREAD

**Issue by rudyares** [mwitkow/grpc-proxy#59]
src.RecvMsg(f) that in handler.forwardClientToServer product 
rpc error: code = Internal desc = grpc: failed to unmarshal the received message string field contains invalid UTF-8

**Comment by fuhrmannb** [comment]
On my side, https://github.com/mwitkow/grpc-proxy/pull/62 patch resolves this issue when I hit the error (in a server stream case, not sure it's related).

**Comment by LcritZ** [comment]
> On my side, https://github.com/mwitkow/grpc-proxy/pull/62 patch resolves this issue when I hit the error (in a server stream case, not sure it's related).

yep,use emptypb can solve it. may need to dig in source code know the reason why the two different

**Comment by dlakshma** [comment]
Using Empty solving the same issue in my use case also. Is there reason why this PR request is still open and not merged to main ?
