### ISSUE TITLE
How is it different from grpc-gateway

### ISSUE THREAD

**Issue by pcj** [mwitkow/grpc-proxy#7]
Might be "obvious", but would be good to explain/address this directly in the README.

Thanks.

**Comment by deejross** [comment]
I just started looking at this to solve a problem that I currently have, so I can answer this. The grpc-gateway is a REST service that talks to gRPC for the purpose of supporting clients that only speak REST. This allows you to put multiple grpc services, running on different ports behind a single endpoint (port). When using something like a load balancer which is just a DNS name, you would either need entries for each service and port in the LB, or you could have just one, put all your services behind this and point the LB to just a single port and let this decide which service gets the request coming from the LB.

Hope that makes sense.

**Comment by pcj** [comment]
Thanks.
