### ISSUE TITLE
Proxy Director

### ISSUE THREAD

**Issue by Gobonoid** [mwitkow/grpc-proxy#8]
According to your comment 
```
// Provide sa simple example of a director that shields internal services and dials a staging or production backend.
// This is a *very naive* implementation that creates a new connection on every request. Consider using pooling.
```
from https://github.com/mwitkow/grpc-proxy/blob/master/proxy/examples_test.go#L37

I've tried to implement pooling for my connections. Unfortunately connection pooling is not possible. *grpc.ClientConn is struct not interface hence I can't inject *grpc.ClientConn into composition with Close method that would return connection to the pool. That means I have to create connection every time it's requested.

Do you know any other way of optimization? Or maybe example from examples_test.go is not that scary?

**Comment by mwitkow** [comment]
You do not have to return a connection to the pool. You can use the same `grpc.ClientConn` across multiple go-routines with multiple requests concurrently.

**Comment by mwitkow** [comment]
Here's an example of a backend pool implementation:

https://github.com/mwitkow/kfe/tree/master/grpc
