### ISSUE TITLE
panic when proxying route_guide from grpc/examples

### ISSUE THREAD

**Issue by jwfang** [mwitkow/grpc-proxy#9]
my proxy server code:

```go
package main

import (
  "log"
  "net"

  "github.com/mwitkow/grpc-proxy/proxy"
  "golang.org/x/net/context"
  "google.golang.org/grpc"
)

func myDirector(ctx context.Context, fmn string) (*grpc.ClientConn, error) {
  return grpc.DialContext(ctx, "127.0.0.1:10001",
        grpc.WithCodec(proxy.Codec()),
        grpc.WithInsecure())
}

func main() {
  l, err := net.Listen("tcp", "127.0.0.1:10000")
  if err != nil {
    log.Fatalln(err)
  }
  s := grpc.NewServer(
        grpc.CustomCodec(proxy.Codec()),
        grpc.UnknownServiceHandler(proxy.TransparentHandler(myDirector)))
  if err := s.Serve(l); err != nil {
    log.Fatalln(err)
  }
}
```

i got the following error when proxy the route_guide example come with grpc:

> panic: send on closed channel
> 
> goroutine 36 [running]:
> github.com/mwitkow/grpc-proxy/proxy.(*handler).forwardServerToClient.func1(0x9f9e40, 0xc42007f900, 0xc420178180, 0x9f9de0, 0xc4200e1180)
>         /home/vagrant/src/ggrpc/src/github.com/mwitkow/grpc-proxy/proxy/handler.go:151 +0x12f
created by github.com/mwitkow/grpc-proxy/proxy.(*handler).forwardServerToClient
>         /home/vagrant/src/ggrpc/src/github.com/mwitkow/grpc-proxy/proxy/handler.go:159 +0x89
> exit status 2

**Comment by mwitkow** [comment]
@jwfang can you check if you still got the issue after the streaming was fixed?
